### PR TITLE
core: Add libusb_get_max_iso_packet_size_for_alt_setting

### PR DESCRIPTION
**Pull request by aib**
As discussed in #36, [old issue #77](https://sourceforge.net/p/libusb/mailman/libusb-devel/thread/056.8f7cf80ce90539817d58effd879129d7@libusb.org/) and [the mailing list](https://sourceforge.net/p/libusb/mailman/libusb-devel/thread/4D52A463.5080108@redhat.com/).

(I don't have much more to add, but I don't want to sound like a bot, so please feel free to review and thank you!)

### CODE REVIEW

**Comment by tormodvolden** [comment]
In the linked discussions it was suggested a name without "iso" because the function will work for all kind of endpoints. What do you think about that?

**Comment by aib** [comment]
You mean `libusb_get_max_alt_packet_size`? Hmm, yes, maybe it's a better name.

**Comment by tormodvolden** [comment]
Thanks. I guess the internal get_endpoint_max_iso_packet_size() should be renamed too.

**Comment by aib** [comment]
Bumping since it's been a while. Is there anything else to do?

**Comment by tormodvolden** [comment]
Thanks, it is fine. Just want some more reviewers on it since it is an API change/addition, before merging it.

**Comment by tormodvolden** [comment]
This causes the warning (from https://github.com/libusb/libusb/pull/965#issuecomment-1398212517):
```
C:\work\libusb\libusb_staging\libusb\core.c(1124): error C2220: the following warning is treated as an error [C:\work\l
ibusb\libusb_staging\msvc\libusb_dll.vcxproj]
C:\work\libusb\libusb_staging\libusb\core.c(1124): warning C4701: potentially uninitialized local variable 'r' used [C:
\work\libusb\libusb_staging\msvc\libusb_dll.vcxproj]
LINK : fatal error LNK1257: code generation failed [C:\work\libusb\libusb_staging\msvc\libusb_dll.vcxproj]
```
The code is correct, but the compilers are not convinced. I guess initializing r=0 first is the best to do.

**Comment by aib** [comment]
Oops... Fixed.

Also took the opportunity to test the changes on Windows. Working fine!

**Comment by tormodvolden** [comment]
Thanks for testing on Windows! Note that I have already reworked your commits on my staging branch (including the r=0 fix). I suppose your repush right now didn't change anything else.

**Comment by aib** [comment]
That's great, thanks! No, I did not have to change anything else.

**Comment by tormodvolden** [comment]
Merged, thanks for your contribution!

**Pull request closed without merging**
