### PR TITLE
Windows: ignore devices with broken descriptor during enumeration

### PR DESCRIPTION
**Pull request by Youw**
Fixes: https://github.com/libusb/libusb/issues/791

### CODE REVIEW

**Comment by Youw** [comment]
CI is failing for the same reason as on master. Not related to this change.

**Review by dickens — CHANGES_REQUESTED** [review]
This change doesn't make sense to me.  There is no difference between `usbi_sanitize_device()` and `usbi_sanitize_device_descriptor()` and hence no reason to have a new function.

If you want to add a workaround in the Windows backend, then just check the device descriptor before the `memcpy()`.  You probably just need to validate the `bLength` and `bDescriptorType` fields and do your delay if they are not valid.  There is no reason for any changes to the libusb core for this.

**Comment by Youw** [comment]
>  then just check the device descriptor

That makes code/logic duplication, if we're OK with that.

---
My motivation for the change:
The documentation for `usbi_sanitize_device` states that it checks whether the device is valid (a sane assumption: the device has to be fully constructed at that point), and if it is not - it has to be ignored during enumeration.
(The fact that so far each backend fails the entire enumeration if there is a single "broken" device - is a separate discussion. I do believe this has to be applied to all backends.)

My first suggestion for the fix was to return `LIBUSB_ERROR_NO_DEVICE` when `usbi_sanitize_device` fails in the original implementation here: https://github.com/libusb/libusb/blob/a016a082a8143409006d954112b5130bc7e9449c/libusb/os/windows_winusb.c#L1173
but it prints multiple log messages, whereas most of them describe only symptoms of the broken device, not the root reason (broken descriptor).

Simply reuse `usbi_sanitize_device` to check only a descriptor - doesn't seem a good option, because:
- the API/documentation for that function doesn't guarantee that it would only check for the descriptor, and that not fully constructed devices can be passed; (relying on the implementation, rather than on API/documentation is a source of future bugs);

> There is no difference between usbi_sanitize_device() and usbi_sanitize_device_descriptor() and hence no reason to have a new function
- the fact that `usbi_sanitize_device` checks only for a valid descriptor (yet) doesn't mean that it won't change in the future, and not reflected in its API/documentation;

Explicitly separating device check and descriptor check seem like a natural decision (keeps code consistency/gives the ability to reuse new function for other backends).

A cosmetic API addition to `usbi_sanitize_device_descriptor` of an optional context (as compared to `usbi_sanitize_device`) makes it possible to get a single log entry in case of broken device, instead of 20 of them.

---
If my motivation is not good-enough, I'll be happy to update this PR, to check for valid descriptor manually for Windows backend only.

Please confirm.

**Comment by dickens** [comment]
Yes, please take care of this in the Windows backend and leave the core alone.  I'm not worried about code duplication when checking two fields of a structure.

**Pull request closed without merging**
