### PR TITLE
in mingw timespec is contained in parts/time.h which is included by unis...

### PR DESCRIPTION
**Pull request by jjonethal**
...td.h

when configure recognizes unistd.h it shall be used.
Move inclusion of unistd.h up

### CODE REVIEW

**Comment by dickens** [comment]
Can you give more details about what problem(s) you are experiencing?

Regards,
Chris

**Comment by jjonethal** [comment]
When building libusb using mingw
uname -a
MINGW32_NT-6.1 BCHF6KOC 1.0.18(0.48/3/2) 2012-11-21 22:34 i686 Msys
i get a compiler error regarding missing 'struct timespec' declaration.

configure detects timespec included from unistd.h-> parts/time.h
but unistd.h is not getting included on mingw build. So
config.h defines #define HAVE_STRUCT_TIMESPEC 1 
threads_windows.h checks for HAVE_STRUCT_TIMESPEC and does not define struct timespec,
because config.h defined it already.

including unistd.h in libusbi.h for mingw on the proper position build solves that problem for me.
other systems are out of my scope at the moment.

Kind Regards Jean

Making all in libusb
make[2]: Entering directory `/e/cortex/tools/stlink/libusb/libusb'
make[3]: Entering directory `/e/cortex/tools/stlink/libusb/libusb'
  CC     libusb_1_0_la-core.lo
In file included from libusbi.h:237:0,
                 from core.c:44:
./os/threads_windows.h:81:20: warning: 'struct timespec' declared inside parameter list [enabled by default]
       const struct timespec *abstime);
                    ^
./os/threads_windows.h:81:20: warning: its scope is only this definition or declaration, which is probably not what you want [enabled by default]
In file included from core.c:44:0:
libusbi.h:1058:41: warning: 'struct timespec' declared inside parameter list [enabled by default]
  int (*clock_gettime)(int clkid, struct timespec *tp);
                                         ^
  CC     libusb_1_0_la-descriptor.lo
In file included from libusbi.h:237:0,
                 from descriptor.c:29:
./os/threads_windows.h:81:20: warning: 'struct timespec' declared inside parameter list [enabled by default]
       const struct timespec *abstime);
                    ^
./os/threads_windows.h:81:20: warning: its scope is only this definition or declaration, which is probably not what you want [enabled by default]
In file included from descriptor.c:29:0:
libusbi.h:1058:41: warning: 'struct timespec' declared inside parameter list [enabled by default]
  int (*clock_gettime)(int clkid, struct timespec *tp);
                                         ^
  CC     libusb_1_0_la-io.lo
In file included from libusbi.h:237:0,
                 from io.c:40:
./os/threads_windows.h:81:20: warning: 'struct timespec' declared inside parameter list [enabled by default]
       const struct timespec *abstime);
                    ^
./os/threads_windows.h:81:20: warning: its scope is only this definition or declaration, which is probably not what you want [enabled by default]
In file included from io.c:40:0:
libusbi.h:1058:41: warning: 'struct timespec' declared inside parameter list [enabled by default]
  int (*clock_gettime)(int clkid, struct timespec *tp);
                                         ^
io.c: In function 'calculate_timeout':
io.c:1198:18: error: storage size of 'current_time' isn't known
  struct timespec current_time;
                  ^
io.c:1198:18: warning: unused variable 'current_time' [-Wunused-variable]

**Comment by dandev37** [comment]
I am having the same issue and including unistd.h near the beginning of libusbi.h solves it.  Chris, please accept Jean's pull request or modify libusbi.h for us MinGW users.

**Comment by mcuee** [comment]
Please refer to this thread as well.
http://libusb.6.n5.nabble.com/libusb-MinGW-org-build-problem-td5714381.html

The consensus is that it is a MinGW problem (MinGW runtime v3.21).
And MinGW.org team is in the process of fixing it (MinGW runtime v3.21.1
will
fix the issue.
http://thread.gmane.org/gmane.comp.gnu.mingw.user/44416/focus=44420

So I guess it is a moot point to work-around MinGW.org bug inside libusb.

-- 
Xiaofan

**Comment by mcuee** [comment]
MinGW.org change log for reference.

diff --git a/mingwrt/ChangeLog b/mingwrt/ChangeLog
--- a/mingwrt/ChangeLog
+++ b/mingwrt/ChangeLog
@@ -1,5 +1,58 @@
+2015-05-18  Keith Marshall  <keithmarshall@users.sourceforge.net>
+
+ Refactor to avoid possible time_t conflicts across headers.
+
+ * include/parts/time.h (struct timespec): Make it more descriptive of,
+ and better able to accommodate, potential ambiguity relating to...
+ (time_t, __time32_t, __time64_t): ...these typedefs; define them here,
+ whence they may be identically imported into each of...
+ * include/sys/types.h include/time.h include/wchar.h: these; delete
+ duplicate typedefs, and import accordingly.
+
+ * include/sys/types.h: Add licence; general comment additions.
+ (_TYPES_H_): Rename multiple inclusion guard macro...
+ (_SYS_TYPES_H): ...to this.
+
+ * include/time.h: Add licence; general comment/layout adjustments.
+ (_BEGIN_C_DECLS, _END_C_DECLS): Use to wrap extern "C" declarations.
+ (_TIME_T_DEFINED, _TIME32_T_DEFINED, _TIME64_T_DEFINED)
+ (_CLOCK_T_DEFINED): Superfluous guard macros; delete them.
+ (_TIME_H_): Rename multiple inclusion guard macro...
+ (_TIME_H): ...to this.
+
+ * include/unistd.h (nanosleep): Adjust to accommodate redefinition...
+ (struct timespec): ...of this.
+
+ * include/wchar.h: Add licence; general comment/layout adjustments.
+ (_BEGIN_C_DECLS, _END_C_DECLS): Use to wrap extern "C" declarations.
+ [GCC] (system_header): Add pragma, identifying header as such.
+ (_WCHAR_H_): Rename multiple inclusion guard macro...
+ (_WCHAR_H): ...to this.
+
+ ...

**Comment by mcuee** [comment]
Not a libusb problem. Close.

**Pull request closed without merging**
