### PR TITLE
xusb: Fix MAX LUN retrieval handling, kernel attached and claim error messages

### PR DESCRIPTION
**Pull request by tormodvolden**
Great if this can be tested for the various cases.

### CODE REVIEW

**Comment by tormodvolden** [comment]
At least the output is fine with a MSD device that breaks in different ways:
```
Reading Max LUN:
   Failed.
   Operation timed out
```

```
Reading Max LUN:
   Stalled, setting Max LUN to 0

Sending Inquiry:
   send_mass_storage_command: Operation timed out
   Operation timed out
   Input/Output Error
```

**Review by mcuee — APPROVED** [review]

**Comment by mcuee** [comment]
This is change is good.

```
PS C:\work\libusb\libusb_pr1239> .\build\v143\x64\Release\xusb 239a:8120
Using libusb v1.0.26.11779

Opening device 239A:8120...
libusb: warning [hid_open] could not open HID device in R/W mode (keyboard or mouse?) - trying without

Reading device descriptor:
            length: 18
      device class: 0
               S/N: 3
           VID:PID: 239A:8120
         bcdDevice: 0100
   iMan:iProd:iSer: 1:2:3
          nb confs: 1

Reading BOS descriptor: no descriptor

Reading first configuration descriptor:
              total length: 218
         descriptor length: 9
             nb interfaces: 6
              interface[0]: id = 0
interface[0].altsetting[0]: num endpoints = 1
   Class.SubClass.Protocol: 02.02.00
       endpoint[0].address: 81
           max packet size: 0040
          polling interval: 10
              interface[1]: id = 1
interface[1].altsetting[0]: num endpoints = 2
   Class.SubClass.Protocol: 0A.00.00
       endpoint[0].address: 02
           max packet size: 0040
          polling interval: 00
       endpoint[1].address: 82
           max packet size: 0040
          polling interval: 00
              interface[2]: id = 2
interface[2].altsetting[0]: num endpoints = 2
   Class.SubClass.Protocol: 08.06.50
       endpoint[0].address: 83
           max packet size: 0040
          polling interval: 00
       endpoint[1].address: 03
           max packet size: 0040
          polling interval: 00
              interface[3]: id = 3
interface[3].altsetting[0]: num endpoints = 2
   Class.SubClass.Protocol: 03.00.00
       endpoint[0].address: 84
           max packet size: 0040
          polling interval: 08
       endpoint[1].address: 04
           max packet size: 0040
          polling interval: 08
              interface[4]: id = 4
interface[4].altsetting[0]: num endpoints = 0
   Class.SubClass.Protocol: 01.01.00
              interface[5]: id = 5
interface[5].altsetting[0]: num endpoints = 2
   Class.SubClass.Protocol: 01.03.00
       endpoint[0].address: 05
           max packet size: 0040
          polling interval: 00
       endpoint[1].address: 85
           max packet size: 0040
          polling interval: 00

Kernel driver attached for interface 0: (not supported)

Claiming interface 0...

Kernel driver attached for interface 1: (not supported)

Claiming interface 1...

Kernel driver attached for interface 2: (not supported)

Claiming interface 2...

Kernel driver attached for interface 3: (not supported)

Claiming interface 3...

Kernel driver attached for interface 4: (not supported)

Claiming interface 4...

Kernel driver attached for interface 5: (not supported)

Claiming interface 5...
   Failed (error -12) Operation not supported or unimplemented on this platform

Reading string descriptors:
   String (0x01): "Raspberry Pi"
   String (0x02): "Pico W"
   String (0x03): "E66141040387422B"

Reading OS string descriptor: no descriptor

Reading interface association descriptors (IADs) for first configuration:
    nb IADs: 1
      IAD 0:
            bFirstInterface: 0
            bInterfaceCount: 2
             bFunctionClass: 02
          bFunctionSubClass: 02
          bFunctionProtocol: 00
                  iFunction: 0

Reading Max LUN:
   Stalled, setting Max LUN to 0

Sending Inquiry:
   sent 6 CDB bytes
   Operation timed out
   Input/Output Error
```

**Comment by mcuee** [comment]
Another device:

```
PS C:\work\libusb\libusb_pr1239> .\build\v143\x64\Release\xusb 04d8:0057
Using libusb v1.0.26.11779

Opening device 04D8:0057...

Reading device descriptor:
            length: 18
      device class: 239
               S/N: 0
           VID:PID: 04D8:0057
         bcdDevice: 0001
   iMan:iProd:iSer: 1:2:0
          nb confs: 1

Reading BOS descriptor: no descriptor

Reading first configuration descriptor:
              total length: 98
         descriptor length: 9
             nb interfaces: 3
              interface[0]: id = 0
interface[0].altsetting[0]: num endpoints = 2
   Class.SubClass.Protocol: 08.06.50
       endpoint[0].address: 81
           max packet size: 0040
          polling interval: 01
       endpoint[1].address: 01
           max packet size: 0040
          polling interval: 01
              interface[1]: id = 1
interface[1].altsetting[0]: num endpoints = 1
   Class.SubClass.Protocol: 02.02.01
       endpoint[0].address: 82
           max packet size: 000A
          polling interval: 02
              interface[2]: id = 2
interface[2].altsetting[0]: num endpoints = 2
   Class.SubClass.Protocol: 0A.00.00
       endpoint[0].address: 03
           max packet size: 0040
          polling interval: 00
       endpoint[1].address: 83
           max packet size: 0040
          polling interval: 00

Kernel driver attached for interface 0: (not supported)

Claiming interface 0...

Kernel driver attached for interface 1: (not supported)

Claiming interface 1...

Kernel driver attached for interface 2: (not supported)

Claiming interface 2...

Reading string descriptors:
   String (0x01): "Microchip Technology Inc."
   String (0x02): "Microchip Composite Device"

Reading OS string descriptor: no descriptor

Reading interface association descriptors (IADs) for first configuration:
    nb IADs: 1
      IAD 0:
            bFirstInterface: 1
            bInterfaceCount: 2
             bFunctionClass: 02
          bFunctionSubClass: 02
          bFunctionProtocol: 01
                  iFunction: 0

Reading Max LUN:
   Max LUN = 0

Sending Inquiry:
   sent 6 CDB bytes
   received 36 bytes
   VID:PID:REV "Microchp":"Mass Sto":"0001"
   Mass Storage Status: 00 (Success)

Reading Capacity:
   sent 10 CDB bytes
   received 8 bytes
   Max LBA: 00000011, Block Size: 00000200 (0.00 GB)
   Mass Storage Status: 00 (Success)

Attempting to read 512 bytes:
   sent 10 CDB bytes
   READ: received 512 bytes
   Mass Storage Status: 00 (Success)

  00000000  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  00000010  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  00000020  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  00000030  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  00000040  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  00000050  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  00000060  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  00000070  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  00000080  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  00000090  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  000000a0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  000000b0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  000000c0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  000000d0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  000000e0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  000000f0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  00000100  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  00000110  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  00000120  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  00000130  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  00000140  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  00000150  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  00000160  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  00000170  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  00000180  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  00000190  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  000001a0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  000001b0  00 00 00 00 00 00 00 00 f5 8b 16 ea 00 00 80 01  ................
  000001c0  01 00 01 07 ff e6 01 00 00 00 11 00 00 00 00 00  ................
  000001d0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  000001e0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  000001f0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 55 aa  ..............U.

Releasing interface 0...
Releasing interface 1...
Releasing interface 2...
Closing device...

```

**Comment by mcuee** [comment]
If I do not replace the USB Mass Storage driver to WinUSB for the above Microchip FW, then the output is like the following.

```
PS C:\work\libusb\libusb_pr1239> .\build\v143\x64\Release\xusb 04d8:0057
Using libusb v1.0.26.11779

Opening device 04D8:0057...

Reading device descriptor:
            length: 18
      device class: 239
               S/N: 0
           VID:PID: 04D8:0057
         bcdDevice: 0001
   iMan:iProd:iSer: 1:2:0
          nb confs: 1

Reading BOS descriptor: no descriptor

Reading first configuration descriptor:
              total length: 98
         descriptor length: 9
             nb interfaces: 3
              interface[0]: id = 0
interface[0].altsetting[0]: num endpoints = 2
   Class.SubClass.Protocol: 08.06.50
       endpoint[0].address: 81
           max packet size: 0040
          polling interval: 01
       endpoint[1].address: 01
           max packet size: 0040
          polling interval: 01
              interface[1]: id = 1
interface[1].altsetting[0]: num endpoints = 1
   Class.SubClass.Protocol: 02.02.01
       endpoint[0].address: 82
           max packet size: 000A
          polling interval: 02
              interface[2]: id = 2
interface[2].altsetting[0]: num endpoints = 2
   Class.SubClass.Protocol: 0A.00.00
       endpoint[0].address: 03
           max packet size: 0040
          polling interval: 00
       endpoint[1].address: 83
           max packet size: 0040
          polling interval: 00

Kernel driver attached for interface 0: (not supported)

Claiming interface 0...
   Failed (error -12) Operation not supported or unimplemented on this platform

Kernel driver attached for interface 1: (not supported)

Claiming interface 1...

Kernel driver attached for interface 2: (not supported)

Claiming interface 2...

Reading string descriptors:
   String (0x01): "Microchip Technology Inc."
   String (0x02): "Microchip Composite Device"

Reading OS string descriptor: no descriptor

Reading interface association descriptors (IADs) for first configuration:
    nb IADs: 1
      IAD 0:
            bFirstInterface: 1
            bInterfaceCount: 2
             bFunctionClass: 02
          bFunctionSubClass: 02
          bFunctionProtocol: 01
                  iFunction: 0

Reading Max LUN:
   Stalled, setting Max LUN to 0

Sending Inquiry:
libusb: error [composite_submit_bulk_transfer] unable to match endpoint to an open interface - cancelling transfer
   send_mass_storage_command: Entity not found
libusb: error [composite_submit_bulk_transfer] unable to match endpoint to an open interface - cancelling transfer
   Entity not found
   Input/Output Error
```

**Comment by tormodvolden** [comment]
Thanks for testing! It looks good.

About the errors in the last run (my patch shouldn't affect those), maybe xusb shouldn't try running test_mass_storage if it can't claim the relevant interface. But this would make it much more complex.

**Pull request closed without merging**
