### PR TITLE
Put extra data under parent interface instead of endpoint

### PR DESCRIPTION
**Pull request by bariscelik**
The subdescriptors that come after the first endpoint was being saved as extra data of **endpoint**. I guess this was because endpoint descriptors always at last of sub-descriptors.

But in my case, I'm using a UVC camera and it sends endpoint descriptors with mixed order. 

As a solution, extra data comes after the endpoint descriptors, have been added as sub-descriptors of related **interface**.

Note: I'm not sure the solution meets USB standards, maybe the way my camera works is wrong

### CODE REVIEW

**Comment by mcuee** [comment]
Please post the USB descriptors of your USB device, for example, using "lsusb -vvv" and Windows USBView or macOS USBProber app.

It could be your device is faulty as per the USB specifications.

**Comment by mcuee** [comment]
I tend to believe the device is non compliant and thus the patch is not valid.

**Comment by mcuee** [comment]
But I will leave this issue open and maybe others can comment further.

**Comment by tormodvolden** [comment]
What does your patch do if the extra data actually belongs to the endpoint?

**Comment by bariscelik** [comment]
> What does your patch do if the extra data actually belongs to the endpoint?

As far as I've seen so far, there is no standard for extra data for endpoints. Also, endpoint descriptors are usually under the regarded interface in a hierarchical order.

**Comment by mcuee** [comment]
Closing this one as it is not valid. Please reopen if you have new updates.

**Pull request closed without merging**
