### PR TITLE
Move to brew bundle

### PR DESCRIPTION
**Pull request by stephengroat**
improved dependency management with brew bundle

`bundle` allows for the package to be upgrade or install, doesn't return 1 if package is already installed

### CODE REVIEW

**Comment by stephengroat** [comment]
the `.travis.yml` could also be updated with `brew bundle cleanup --force` [to remove unneeded preinstalled `brew` formulas](https://github.com/Homebrew/homebrew-bundle#cleanup), which include `libusb`

**Comment by hjelmn** [comment]
Please squish all of this into a single commit.

**Comment by stephengroat** [comment]
sorry about that, now a single

**Comment by hjelmn** [comment]
Ok, looks good. Replacing by #451 which increments the nano version.

**Pull request closed without merging**
