### PR TITLE
core: Avoid mutex lock while printing error and warning

### PR DESCRIPTION
**Pull request by tormodvolden**
AFAICS the mutex was only ensuring consistency across the two "if" comparisons. So instead use a temporary variable for this.

### CODE REVIEW

**Comment by tormodvolden** [comment]
The original plan was to use atomic_load(), but that only works with atomic_t and thus failed on macOS. I guess the mutex lock will then still be needed to ensure atomic access. But limit it as much as possible.

**Comment by tormodvolden** [comment]
@dmitry-zakablukov Maybe you can help to review this?

**Comment by dmitry-zakablukov** [comment]
@tormodvolden , I have looked on changes, looks good to me. But I can't add myself as a reviewer to approve this pr.

**Comment by tormodvolden** [comment]
Thanks! Yes, I tried to add you through the GitHub Reviewers function too, it didn't work, but it is not so important either. I can add a Reviewed-By: to the commit message, which I find better anyway.

**Pull request closed without merging**
