### PR TITLE
Minor fix to documentation

### PR DESCRIPTION
**Pull request by TahomaSoft**
Fixed a couple of errors that were revealed by running Doxygen. 

Changed two lines in doxygen.cfg.in to comment out deprecated setting and fixed paper size from invalid a4wide to a4.

### CODE REVIEW

**Comment by tormodvolden** [comment]
You'll probably need to squash the commits or rebase, basically only leaving the last commit.

**Comment by LudovicRousseau** [comment]
I fixed in issue by upgrading the config file in https://github.com/libusb/libusb/commit/90273023db02ed747f6d5f3658d43015d14f8d46

Thanks for the notice

**Comment by TahomaSoft** [comment]
Thank you, and you are welcome!

**Comment by tormodvolden** [comment]
The suggested change of PAPER_TYPE is still applicable. The current value of "a4wide" is not listed as a valid value.

**Comment by LudovicRousseau** [comment]
@tormodvolden  exact. Fixed in https://github.com/libusb/libusb/commit/bda2344f5e7d460decd3968492faa7a5fb2797cd

**Pull request closed without merging**
