### PR TITLE
Added a clang-tidy config file

### PR DESCRIPTION
**Pull request by seanm**
All checks are enabled except for those that cause any warning.

This is a starting point, some of the currently-supressed warnings can be fixed hereafter.

### CODE REVIEW

**Comment by Youw** [comment]
I think it is best to introduce things like this along with the CI script to run/check it.
It is not implicitly used by any of the existing tools, right?

**Comment by Youw** [comment]
And I agree - a very good starting point.

**Comment by seanm** [comment]
> I think it is best to introduce things like this along with the CI script to run/check it.

Agreed. But I don't know anything about github CI, hopefully someone else can integrate this.

At least this file allows developers to use clang-tidy locally.

>It is not implicitly used by any of the existing tools, right?

Correct; as far as I know.

**Comment by hjelmn** [comment]
Do we want to take this one step further and add clang-format as a prerequisite?

**Comment by seanm** [comment]
> Do we want to take this one step further and add clang-format as a prerequisite?

Did you mean clang-tidy? clang-format is an orthogonal discussion. I had started work on clang-format, but waiting reply here: https://github.com/libusb/libusb/pull/1421#issuecomment-1873605415

**Comment by hjelmn** [comment]
I mean both. I kind of want to set minimum standards on commits.

**Comment by seanm** [comment]
> I mean both. I kind of want to set minimum standards on commits.

I'm all for clang-format too. But it's unrelated to clang-tidy and this PR. Let's move the discussion here: https://github.com/libusb/libusb/issues/1442

**Comment by seanm** [comment]
@tormodvolden for example, if this was merged to master, then I (and others) could be using clang-tidy to check our work in other branches.

**Review by Youw — APPROVED** [review]
#1457

**Comment by seanm** [comment]
@tormodvolden @hjelmn is there any reason to not just merge this? It can't break anything else, it's just a config file...

**Pull request closed without merging**
