### PR TITLE
Fix Zero-Length Packet on Macos

### PR DESCRIPTION
**Pull request by fabiensanglard**
The ZLPs are not being sent when they should because we retrieve
    and incorrect value for wMaxPacketSize via GetPipePropertiesV3.
    GetEndpointPropertiesV3 is what we need.

### CODE REVIEW

**Comment by seanm** [comment]
Look reasonable, though I'm no expert in this area.

Small typo in commit message: "and incorrect value" -> "an incorrect value"

Personally, I would also put more of the info from https://github.com/libusb/libusb/issues/1581 into the commit message itself. (git commit history will outlive github I'd wager.)

**Comment by fabiensanglard** [comment]
- Fixed typo in commit message.
- Elaborated on the commit message to describe error better.

**Comment by tormodvolden** [comment]
I hope there is no other code relying on darwin_get_pipe_properties() returning the "cooked" values (multiplied by burst and mul)?

**Comment by fabiensanglard** [comment]
I checked that before uploading this PR. The method `darwin_get_pipe_properties` is called in three locations.

1. `submit_bulk_transfer`. `wMaxPacketSize` is used there and we are fixing it.
2. `submit_iso_transfer`. Only uses field `interval`.
3. `get_endpoints`. Only uses `direction` and `number`.

The cooked value was only used `submit_bulk_transfer` so I don't think this is breaking anything else.

**Comment by tormodvolden** [comment]
Thanks a lot for checking and confirming this.

**Comment by tormodvolden** [comment]
Do you know what the pre-550 interface version would return in this case? (If it supports USB3, I dunno). Just so that darwin_get_pipe_properties() would be consistent over all versions.

**Comment by tormodvolden** [comment]
I just wonder if it is by convention that /pipe/ properties include the multipliers whereas /endpoint/ properties don't. And the name of our (internal) function darwin_get_pipe_properties() could be misleading in this case. But you have added comments about this so it should be OK.

**Comment by fabiensanglard** [comment]
> Do you know what the pre-550 interface version would return in this case? (If it supports USB3, I dunno). Just so that darwin_get_pipe_properties() would be consistent over all versions.

Good call. According to its doc, function `GetPipeProperties` [returns](https://lab.qaq.wiki/Lakr233/IOKit-deploy/-/blob/master/IOKit/usb/IOUSBLib.h#L2412) the FULL maxPacket size. So it does support USB3. I can add a call to `GetEndpointProperties` to fix it there too.

That being said  [iousbdeviceinterface500](https://developer.apple.com/documentation/iokit/iousbdeviceinterface500), was included with `macOS 10.7.3`, which was [release in 2012](https://apple.fandom.com/wiki/Mac_OS_X_10.7.3#:~:text=3%20is%20an%20update%20to,Apple%20on%20February%201%2C%202012.). 

1. Do we want to support a 13 years old OS?
2. Regardless if we want to support it or not, the behavior should be consistent. So either we delete the fallback call to `GetPipeProperties` or we fix it with a subsequent call to `GetEndpointProperties`.

**Comment by tormodvolden** [comment]
1. If the effort is minimal, I'd say yes. If we have larger problems we can ditch it. We are not Apple :) The percentage may be much higher in labs etc where libusb is in use, compared to the general consumer market.
2. Maybe leaving darwin_get_pipe_properties() to return the full "pipe" property is cleaner, and rather do the division in the caller, as was also suggested in the bug report?

**Comment by tormodvolden** [comment]
Sounds good. If in the future some function will need the cooked value, we can e.g. add a full_max_packet_size to struct darwin_pipe_properties.

**Pull request closed without merging**
