### PR TITLE
Fix ISOCH by returning actual subapi in winusb_copy_transfer_data rat…

### PR DESCRIPTION
**Pull request by kahluwalia**
…her than SUB_API_NOTSET

### CODE REVIEW

**Comment by tormodvolden** [comment]
Thanks for the patch submission. It would be great to improve Windows ISOCH. This needs to be reviewed carefully. I do remember from going through subapi stuff (but not ISOCH, and all this some time ago) and that "NOTSET" was used to defer the selection to another place. Do you have more evidence, like debug log before and after?

**Comment by tormodvolden** [comment]
This was introduced in commit 9c28ad21 and that commit did so many things that it is hard to understand what was intended. It does look like winusbx_copy_transfer_data() expects the actual sub_api to be passed.

**Comment by kahluwalia** [comment]
I've changed the way the sub_api is determined - it is now done inside winusbx_copy_transfer_data(). It seems this is more in line with all the other winusbx_XXX functions and I hope it reduces the chances this change can affect any of the other implementations.

@tormodvolden I haven't got any logs, but a change was required to determine the sub_api to get ISOCH mode working on an IN endpoint with the WinUSB driver.

**Comment by tormodvolden** [comment]
[I mentioned #749 above but it looks like GitHub doesn't display it]

Thanks a lot, now it looks pretty close to the fix suggested in #749, which maybe is slightly more efficient in the non-isoch case.

**Comment by kahluwalia** [comment]
@tormodvolden aligned with https://github.com/libusb/libusb/pull/749

**Comment by tormodvolden** [comment]
Great. Do you have a full name for the AUTHORS list (also for the commit log it wouldn't be bad)?

**Comment by kahluwalia** [comment]
@tormodvolden I've tried to add full name to commit - not sure if it worked

**Comment by tormodvolden** [comment]
It worked, thank you.

**Pull request closed without merging**
