### PR TITLE
Fixed -Wformat warnings by casting intptr_t to void*

### PR DESCRIPTION
**Pull request by seanm**

### CODE REVIEW

**Comment by seanm** [comment]
@hjelmn @LudovicRousseau

**Comment by LudovicRousseau** [comment]
Can you please copy/paste the compiler warnings your patch fixes in the commit message?
it is important to know _why_ the change was made.

**Comment by seanm** [comment]
I thought the commit message was pretty clear... Basically: %p is for pointers, not integers.  Here's the exact output from my bot:

```
/libusb/libusb/core.c:1252:33: warning: format specifies type 'void *' but the argument has type 'intptr_t' (aka 'long')
      [-Wformat]
        usbi_dbg("wrap_sys_device %p", sys_dev);
                                  ~~   ^~~~~~~
                                  %ld
In file included from /libusb/libusb/core.c:44:
/libusb/libusb/libusbi.h:241:63: note: expanded from macro 'usbi_dbg'
#define usbi_dbg(...) _usbi_log(NULL, LIBUSB_LOG_LEVEL_DEBUG, __VA_ARGS__)
                                                              ^~~~~~~~~~~
/libusb/libusb/libusbi.h:236:71: note: expanded from macro '_usbi_log'
#define _usbi_log(ctx, level, ...) usbi_log(ctx, level, __FUNCTION__, __VA_ARGS__)
                                                                      ^~~~~~~~~~~
/libusb/libusb/core.c:1276:45: warning: format specifies type 'void *' but the argument has type 'intptr_t' (aka 'long')
      [-Wformat]
                usbi_dbg("wrap_sys_device %p returns %d", sys_dev, r);
                                          ~~              ^~~~~~~
                                          %ld
In file included from /libusb/libusb/core.c:44:
/libusb/libusb/libusbi.h:241:63: note: expanded from macro 'usbi_dbg'
#define usbi_dbg(...) _usbi_log(NULL, LIBUSB_LOG_LEVEL_DEBUG, __VA_ARGS__)
                                                              ^~~~~~~~~~~
/libusb/libusb/libusbi.h:236:71: note: expanded from macro '_usbi_log'
#define _usbi_log(ctx, level, ...) usbi_log(ctx, level, __FUNCTION__, __VA_ARGS__)
                                                                      ^~~~~~~~~~~
2 warnings generated.
```

**Comment by LudovicRousseau** [comment]
Please, in the commit message itself, not in the PR discussion. The PR discussion will be lost, the commit message will stay (forever).
You will have to edit the commit message and push again your Wformat branch.

**Comment by seanm** [comment]
I've updated the commit message for you.

**Comment by LudovicRousseau** [comment]
Pushed in https://github.com/libusb/libusb/commit/2a7372db54094a406a755f0b8548b614ba8c78ec

Thanks a lot

**Pull request closed without merging**
