### PR TITLE
Run cross-platform tests on all CI platforms

### PR DESCRIPTION
**Pull request by RReverser**
See discussion in #1348.

Creating as a draft PR for now as I'm sure this will blow up on some platform or the other.

### CODE REVIEW

**Comment by RReverser** [comment]
Well that was interesting. Even `init_context` fails on the netlink tests?

Going to sleep for now, will look into this later.

**Comment by RReverser** [comment]
@mcuee  This one should be ready to go too.

**Comment by mcuee** [comment]
@tormodvolden 

This should be a good improvement. Please help to review. Thanks.

**Comment by tormodvolden** [comment]
Sounds good. You can anyway make that new PR on top of this. I might squash this a bit (leaving out the LIBUSB_CALL fix separately) but I won't change anything.

**Comment by RReverser** [comment]
Also noticed that the scripts weren't passing all the extended warning options to CXXFLAGS, so C++ backends like Haiku or Emscripten didn't have those enabled. Fixed that here too.

**Comment by RReverser** [comment]
Wow AppVeyor is so slow it hit its own timeout... At some point it's probably worth migrating those over to Github Actions windows runner.

I'll do a dummy push to force CI rerun.

**Comment by RReverser** [comment]
I guess appveyor is just slow today, random "Build execution time has reached the maximum allowed time for your plan (60 minutes)." again but on different configs.

Shouldn't be related to changes.

**Comment by tormodvolden** [comment]
It is the "Uploading artifacts..." part that takes so long, probably the receiving file server is bogged down.

**Comment by RReverser** [comment]
Okay, so... let's merge this? :)

I'd like to rebase other PRs on top of this, since it's becoming harder to manage dependency chain (ideal order being: this PR -> #1351 -> #1339).

**Comment by tormodvolden** [comment]
Merged in commit dfed0d16. Thanks!

As you might have seen we have a backlog of merge requests because we don't have enough people (and specific skills for) reviewing them. We want right now to focus on releasing 1.0.27 RSN so that means even less time for reviewing in the meantime. However I am interesting in getting your CI testing in because that can save (or compensate for the lack of) a lot of manual testing during the release testing.

**Comment by RReverser** [comment]
Yeah I've seen that and it's totally fair.

I think you don't need to block 1.0.27 on further WebUSB improvements (even though it would be nice to get them in for symbolic reasons) since Wasm users need to build libusb from source anyway, and don't rely on distro releases as much.

But the testing parts are something that I'm definitely interested in landing sooner rather than later because it helps more than just WebUSB alone, and makes further improvements easier by, well, automatically verifying that the changes still work.

**Comment by RReverser** [comment]
@tormodvolden I just realised that this PR doesn't cover Windows tests. It covers Linux, macOS, MinGW + MSYS2, AppVeyor MinGW+MSYS2, but not AppVeyor MSVC because those use custom Batch commands in appveyor.yml and not ci-build.sh.

I think I'll leave those for someone else to add, just wanted to bring it to attention.

**Pull request closed without merging**
