### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by dickens**
This is a collection of miscellaneous fixes, mostly for Windows. If all the builds pass and there are no objections, I plan to merge this weekend.

### CODE REVIEW

**Comment by hiyuh** [comment]
IMHO, use `AX_PTHREAD` from `autoconf-archive`?

**Comment by diabolo38** [comment]
while looking at some of the patch , i was a bit surprises to see timing uisage of CLOCK_REALTIME i would have expected CLOCK_MONOTONIC.

**Comment by dickens** [comment]
Why are you surprised? The gettimeofday() function reads the realtime clock, so this is a direct replacement. The actual clock source for the logging doesn't matter much as we use a reference time to start at 0 anyway.

**Comment by diabolo38** [comment]
yes perfectly fine for log we don"t quiet care of some jump or roll back  , after more in depth sight i find that  CLOCK_MONOTONIC is well used for all time out . sorry for the stupid remarks  :( .

**Pull request merged**
