### PR TITLE
Update windows_winusb.c

### PR DESCRIPTION
**Pull request by ramazan-mamuchiev**
Windows: crash on init_device

### CODE REVIEW

**Comment by ramazan-mamuchiev** [comment]
This PR fixed issue https://github.com/libusb/libusb/issues/731

**Comment by ramazan-mamuchiev** [comment]
@dickens Please have a look to this PR

**Comment by ramazan-mamuchiev** [comment]
@LudovicRousseau Please have a look to this PR

**Comment by dickens** [comment]
I'd like to understand how we are ending up in this situation in the first place.  Every device should have an ancestor terminating at a HCD hub.  Can you provide a debug log?

**Comment by ramazan-mamuchiev** [comment]
@dickens Please merge this PR. I still waiting it, because I need update usage commit of libusb in my source code. Here just fixed using invalid(null) pointer to prevent crashing whole application.

**Comment by dickens** [comment]
> @dickens Please merge this PR. I still waiting it, because I need update usage commit of libusb in my source code. Here just fixed using invalid(null) pointer to prevent crashing whole application.

Without finding the appropriate ancestor, the device will end up getting assigned a bus number of 0, which is not valid.  I'm sorry, but it is necessary to understand _how_ this situation is being encountered.

**Comment by ramazan-mamuchiev** [comment]
Sorry, But I can't provide anymore information.

**Comment by dickens** [comment]
> Sorry, But I can't provide anymore information.
> I was hoping that fault tolerance is more important to you, but I was wrong.

Your change is not introducing fault tolerance, it is papering over an issue that is not understood.  Unless further information can be provided, I will close this for now.

**Pull request closed without merging**
