### PR TITLE
Fix typo mantisa -> mantissa

### PR DESCRIPTION
**Pull request by fabiensanglard**
The correct spelling is "mantisSa"

### CODE REVIEW

**Comment by fabiensanglard** [comment]
This is a change in the API but these structure were merged recently and have not been published in a stable release. I think it is fine to fix the typo.

**Comment by fabiensanglard** [comment]
@mcuee and @tormodvolden please take a look

**Comment by mcuee** [comment]
> This is a change in the API but these structure were merged recently and have not been published in a stable release. I think it is fine to fix the typo.

I agree with you. But I will let @tormodvolden to decide.

**Review by Youw — APPROVED** [review]
LGTM.
This hasn't been released yet and just recently added. Better to fix now, while it doesn't impact too many users (if any).

**Review by seanm — APPROVED** [review]

**Comment by tormodvolden** [comment]
Yes, there is no problem fixing up the API before it has been published. Thanks for taking a double look!

We did a less than stellar job at reviewing this. The spelling was not even consistent with the code comments. Curiously, codespell wouldn't have caught "mantisa" even in a comment. It does find these though, introduced in the same commit:
```
$ codespell libusb
libusb/descriptor.c:1008: ony ==> only, on, one
libusb/descriptor.c:1028: re-use ==> reuse
```
Further, maybe we should spell superspeed+/SuperSpeed+/SuperSpeedPlus consistently, also for better searchability?

Apart from certain platform files in os/* we use classic style /* */ for comments and not the C++ style // up to now almost consistently, so it we shouldn't diverge here.

Can you please fix up these as well? In the meantime I'll merge the present API change, it is worth having it separately from cosmetic changes in any case.

**Comment by fabiensanglard** [comment]
@tormodvolden: All done in PR #1502 1502

**Pull request closed without merging**
