### PR TITLE
Fix for Issue #1169: libusb with old MacOS 10.11.6 El Captain

### PR DESCRIPTION
**Pull request by seanm**

### CODE REVIEW

**Comment by tormodvolden** [comment]
There is an AC_CHECK_HEADERS([IOKit/usb/IOUSBHostFamilyDefinitions.h]) in configure.ac that will define the HAVE_IOKIT_USB_IOUSBHOSTFAMILYDEFINITIONS_H macro if available. This was added in commit f8dc6af9.

**Comment by tormodvolden** [comment]
About the version checks, commit 00688d05 says "This check inadvertently disables features for other Apple platforms that
use IOKit." So it sounds like putting these checks back will break something on some platforms.

**Comment by tormodvolden** [comment]
@osy Can you explain a bit more on commit 00688d0? I scanned through issue #911 but could not see anything about other Apple platforms.

**Comment by osy** [comment]
> @osy Can you explain a bit more on commit [00688d0](https://github.com/libusb/libusb/commit/00688d059262b291d1bf9ef48865f0d3e0a48952)? I scanned through issue #911 but could not see anything about other Apple platforms.

https://github.com/libusb/libusb/issues/1169#issuecomment-1220390750

**Comment by tormodvolden** [comment]
We could use a copy of MAC_OS_X_VERSION_MIN_REQUIRED that we set to a dummy (high) value for other Apple platforms. Or something less hacky...

**Comment by osy** [comment]
That could work but there’s also different versions of the iokit interface for iOS as well (and other apple os). However, this is probably what I will end up doing in a patch when building libusb for iOS.

**Comment by seanm** [comment]
>there’s also different versions of the iokit interface for iOS as well (and other apple os).

@osy can you point me to where?  I can't find IOUSBLib.h in any other Xcode SDK besides the macOS SDK:

```
% find /Applications/Xcode.app/Contents/Developer/Platforms -name IOUSBLib.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Versions/A/Headers/usb/IOUSBLib.h
```

**Comment by seanm** [comment]
>There is an AC_CHECK_HEADERS([IOKit/usb/IOUSBHostFamilyDefinitions.h]) in configure.ac that will define the HAVE_IOKIT_USB_IOUSBHOSTFAMILYDEFINITIONS_H macro if available. This was added in commit https://github.com/libusb/libusb/commit/f8dc6af91607d5d2202c47b3b62e107df9197184.

@tormodvolden oh interesting. Does it build the string `HAVE_IOKIT_USB_IOUSBHOSTFAMILYDEFINITIONS_H` based on the parameters to `AC_CHECK_HEADERS`?

Still, this check only benefits autotools builds, it doesn't do anything for the Xcode project, where `HAVE_IOKIT_USB_IOUSBHOSTFAMILYDEFINITIONS_H` will never be defined.

My oldest Mac that I can easily VNC to is 10.10 Yosemite, and I can confirm the `IOKit/usb/IOUSBHostFamilyDefinitions.h` is *not* there. And `HAVE_IOKIT_USB_IOUSBHOSTFAMILYDEFINITIONS_H` is not defined so the #include is not attempted.  But everything builds anyway...

 And on my 12.0 Monterey system, `IOKit/usb/IOUSBHostFamilyDefinitions.h` does exist, but the Xcode project builds fine with including that file.

So I'm not sure the point of including `IOKit/usb/IOUSBHostFamilyDefinitions.h`... maybe it's needed for some macOS version in between?

**Comment by tormodvolden** [comment]
> oh interesting. Does it build the string `HAVE_IOKIT_USB_IOUSBHOSTFAMILYDEFINITIONS_H` based on the parameters to `AC_CHECK_HEADERS`?

Yes, AC_CHECK_HEADER(x/y.h) will define HAVE_X_Y_H if the header file is found.

**Comment by Youw** [comment]
I wouldn't touch the `IOUSBHostFamilyDefinitions.h` simply because it doesn't do any harm and not directly related to this change/fix.

**Comment by mcuee** [comment]
@hjelmn 

Is this PR is still required if PR #1266 is reviewed to be good?

**Comment by tormodvolden** [comment]
With #1266 merged, can we close this one now?

**Comment by mcuee** [comment]
Ping @seanm and @hjelmn.

**Comment by seanm** [comment]
Yes, this is obsolete. Closing.

**Pull request closed without merging**
