### PR TITLE
Fixed many compiler warning about sign and size mismatch

### PR DESCRIPTION
**Pull request by seanm**
- added various casts
- assed some asserts where the casts made assumptions
- enabled additional warnings in Xcode project

### CODE REVIEW

**Comment by LudovicRousseau** [comment]
I would prefer to have:

- different commit for different issues
- the compiler warning the commit is fixing

**Comment by seanm** [comment]
I didn't really fix any 'issue', I just enabled some warning flags in the Xcode project (Xcode/common.xcconfig) and fixed them.

Not sure what kind of granularity you think'd be best... do you find it too big to review?

**Comment by LudovicRousseau** [comment]
Without the compiler warnings I can't tell if the change is correct or needed.
My preferred form of patch is like this one https://github.com/LudovicRousseau/libusb/commit/8e9c6f38e0d82c8a5dce1eb93062b0ad05c9f4a5
Yes, it is much more work to create the commit message.

Maybe another libusb maintainer will accept your patch as-is.

**Comment by hjelmn** [comment]
@LudovicRousseau That seems reasonable. I think he could put them all in one commit if the warnings are all in the commit message. Might get a little messy though. Maybe break it down by component (darwin, io, etc).

**Comment by hjelmn** [comment]
I want this all for the next release for sure though. There is no rush. I was going to see about cutting an rc next week sometime.

**Comment by seanm** [comment]
Well, the warning messages I can create for you just by checking out master and building, here you go:

from clang -Wshorten-64-to-32
```
/descriptor.c:65:23: Implicit conversion loses integer precision: 'int' to 'uint16_t' (aka 'unsigned short')
/descriptor.c:1166:19: Implicit conversion loses integer precision: 'int' to 'uint16_t' (aka 'unsigned short')
/os/darwin_usb.c:606:45: Implicit conversion loses integer precision: 'int' to 'uint8_t' (aka 'unsigned char')
/os/darwin_usb.c:711:28: Implicit conversion loses integer precision: 'int' to 'UInt16' (aka 'unsigned short')
/os/darwin_usb.c:713:23: Implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'UInt16' (aka 'unsigned short')
/os/darwin_usb.c:1011:42: Implicit conversion loses integer precision: 'UInt16' (aka 'unsigned short') to 'uint8_t' (aka 'unsigned char')
/os/darwin_usb.c:1174:66: Implicit conversion loses integer precision: 'int' to 'UInt8' (aka 'unsigned char')
/os/darwin_usb.c:1183:26: Implicit conversion loses integer precision: 'int' to 'UInt8' (aka 'unsigned char')
/os/darwin_usb.c:1249:84: Implicit conversion loses integer precision: 'int' to 'UInt8' (aka 'unsigned char')
/os/darwin_usb.c:1273:87: Implicit conversion loses integer precision: 'int' to 'uint8_t' (aka 'unsigned char')
/os/darwin_usb.c:1296:50: Implicit conversion loses integer precision: 'int' to 'uint8_t' (aka 'unsigned char')
/os/darwin_usb.c:1311:52: Implicit conversion loses integer precision: 'int' to 'uint8_t' (aka 'unsigned char')
/os/darwin_usb.c:1432:87: Implicit conversion loses integer precision: 'int' to 'UInt8' (aka 'unsigned char')
/os/darwin_usb.c:1501:70: Implicit conversion loses integer precision: 'int' to 'UInt8' (aka 'unsigned char')
/os/darwin_usb.c:1502:73: Implicit conversion loses integer precision: 'int' to 'UInt8' (aka 'unsigned char')
/os/darwin_usb.c:1528:50: Implicit conversion loses integer precision: 'int' to 'uint8_t' (aka 'unsigned char')
/os/darwin_usb.c:1693:72: Implicit conversion loses integer precision: 'unsigned int' to 'UInt16' (aka 'unsigned short')
```

from cppcheck
```
[examples/sam3u_benchmark.c:58]: (warning) %u in format string (no. 1) requires 'unsigned int' but the argument type is 'signed int'.
[examples/sam3u_benchmark.c:62]: (warning) %u in format string (no. 1) requires 'unsigned int' but the argument type is 'signed int'.
[libusb/os/haiku_usb_backend.cpp:246]: (error) Shifting signed 32-bit value by 31 bits is undefined behaviour
```

I can amend the commit message with that if you'd like.

**Comment by seanm** [comment]
@hjelmn @LudovicRousseau I've fixed the merge conflicts...

**Comment by hjelmn** [comment]
Thanks @seanm. I plan to do another batch this weekend with the hope of getting a release out before the end of the month.

**Pull request closed without merging**
