### PR TITLE
Windows: Support LIBUSB_TRANSFER_ADD_ZERO_PACKET on winusb

### LINKED ISSUE #91: Windows: Add LIBUSB_TRANSFER_ADD_ZERO_PACKET flag to indicate need for ZLP
Ref: http://libusb.org/ticket/6

Linux and Mac OS X backend are ready. But not Windows and OpenBSD/NetBSD backend.

### PR DESCRIPTION
**Pull request by patstew**
Fixes #91

### CODE REVIEW

**Comment by dickens** [comment]
This implementation has one particular shortcoming--the policy is turned on/off globally for an endpoint.

Consider the following scenario:
1) User submits a transfer and requests the ADD_ZERO_PACKET flag. This makes its way to winusbx_submit_bulk_transfer() and the policy gets turned on.
2) Before the first transfer completes, the user submits a second transfer without the ADD_ZERO_PACKET flag. This makes its way to winusbx_submit_bulk_transfer() and the policy gets turned off.
3) After the second transfer is done submitting, the first transfer makes its way out of the WinUSB queue and does not get a ZLP added because the policy is now off.

It would be better to instead manually submit a second zero-length transfer if this flag is present AND the transfer length is a multiple of the endpoint max packet size. The second part is an important point, because a ZLP isn't supposed to be sent unconditionally.

**Comment by hjelmn** [comment]
@patstew Can you update based on @dickens comments?

**Comment by patstew** [comment]
I'd sort of filed this under 'it's good enough for me' for the time being.
I was a little bit concerned about what to do with the overlapped IOs and errors in going about it that way. You've got two transfers in flight now, and what if one fails and the other doesn't? And is it necessary to wait on both, or can you assume that the ZLP completing means that the actual transfer is complete?

**Comment by patstew** [comment]
Even so, you'd now need to have two overlapped structures for each winfd, and decide which to look at to get bytes transferred/complete based on whether it's an emulated ZLP or not. I think that it will end up adding a bunch of complexity in the winusb code, unless I'm missing an easy solution.

I think in most cases you either want ZLP behaviour on an endpoint or not, so I could change this PR so that each endpoint basically adopts the policy of the first transfer, and you get an error if any future transfer tries to change it. It'd be better than the status quo of failing on all ZLPs, it'd be a much smaller change with less to go wrong and I think it would cover 99% of usecases. Would that be acceptable?

**Comment by hjelmn** [comment]
@patstew Sounds good to me. That would address one of the @dickens comments. I can't comment on any of the other comments as I don't know anything about the Windows USB stack.

**Comment by patstew** [comment]
@dickens Do you have any comments about this way of doing it?

**Comment by mcuee** [comment]
I agree that most of the people will want ZLPs always or never, if they are only deal with one device in the application.

**Comment by patstew** [comment]
It's per endpoint, per device, so I don't think it matters how many devices you use in the application.

**Comment by mcuee** [comment]
I see. Thanks for the clarifications.

**Comment by hjelmn** [comment]
Should we take this for 1.0.25? ZLP is a pretty big missing feature from the windows backend but the backend has been bit rotting.

**Comment by mcuee** [comment]
@dickens Just want to know if you still have concerns for the merging of this pull request. Please advice. Thanks.

**Comment by mcuee** [comment]
I am fine with this pull request myself. I think we can take a bit of risk and merge the pull request. It will not really affect existing Windows user since it is a new feature.

**Pull request closed without merging**
