### PR TITLE
Some WIP with 2 small fixes to merge

### PR DESCRIPTION
**Pull request by seanm**
@dickens @hjelmn I see that you are planning a release shortly, so you are probably being very conservative in what you merge at this point, but please at least cherry pick these two:

e4851c3
e6fbd27

anything else you can merge now or after the release... thx.

### CODE REVIEW

**Comment by dickens** [comment]
I've merged the following four commits:

568274d extend enum liusb_speed for 10000MBit/s case (as 3f6a48d)
e4851c3 Test use of kUSBDeviceSpeedSuper against SDK version (as c8069cd)
e6fbd27 Suppress deprecation warning when building against 10.13 SDK (as 4f9d585)
026e630 Improve error checking to prevent (very unlikely) null dereference (as fef88bf)

The rest we'll take for the next release. Thanks!

**Comment by hjelmn** [comment]
@seanm What in this PR still needs to be brought into master? Its kind of a mess of commits right now.

**Comment by hjelmn** [comment]
@seanm Let me try just cherry-picking those commits into a clean PR. Will need to do so anyway to get the nano updated.

**Comment by hjelmn** [comment]
Looks like all the Dec 29 commits are already merged with exception of "extend enum liusb_speed for 10000MBit/s case".

**Pull request closed without merging**
