### PR TITLE
Android build name correction

### LINKED ISSUE #31: Android: Android build name correction
android/jni/libusb.mk

LOCAL_MODULE := libusb1.0
this should be
LOCAL_MODULE := usb-1.0

"lib" should be dropped as it is not required
"-" should be placed between "usb" and "1.0".

also appropriately update  android/jni/examples.mk 
why important: afaik naming system on desktop is libusb-1.0.so\* not libusb1.0.so*

### PR DESCRIPTION
**Pull request by xloem**
fixes #31

see #143 and #596 for solutions to the whole build system

@adisuciu I'm not presently set up to build for android, are you able to test this and note or fix any bugs?

EDIT: Bugs fixed and squashed.

### CODE REVIEW

**Comment by adisuciu** [comment]
```
+ export USE_PC_NAME=1
+ USE_PC_NAME=1
+ /home/adi/android/sdk/ndk/21.3.6528147/ndk-build clean
Android NDK: APP_PLATFORM not set. Defaulting to minimum supported version android-16.    
/home/adi/android/sdk/ndk/21.3.6528147/build/core/build-binary.mk:651: Android NDK: Module dpfp depends on undefined modules: usb1.0    
/home/adi/android/sdk/ndk/21.3.6528147/build/core/build-binary.mk:664: *** Android NDK: Note that old versions of ndk-build silently ignored this error case. If your project worked on those versions, the missing libraries were not needed and you can remove those dependencies from the module to fix your build. Alternatively, set APP_ALLOW_MISSING_DEPS=true to allow missing dependencies.    .  Stop.
```

probably because https://github.com/libusb/libusb/blob/master/android/jni/examples.mk#L34 

I can try using a variable for the library name and replace it across the mk-files ? the original issue suggested changing the link library name everywhere as it didn't have this "legacy" option.

**Comment by adisuciu** [comment]
Can I add to this PR ? or should I send a diff ?

**Comment by xloem** [comment]
I added you to my repo if you want to push straight to https://github.com/xloem/libusb fix/adisuciu-build-name

**Comment by adisuciu** [comment]
Yes, that was pretty much my fix. It builds correctly. Now I'm rebasing this to the better android support branch and rebuilding my whole application to see if there's anything wrong. I got some library naming errors only after deploying so I want to make sure :) I'll let you know of the result

**Comment by adisuciu** [comment]
Works great !

**Review by adisuciu — APPROVED** [review]

**Comment by xloem** [comment]
I've rebased and squashed this to make it more mergeable.

**Comment by mcuee** [comment]
@hjelmn This should be save to merge. Thanks.

**Review by mcuee — APPROVED** [review]

**Pull request closed without merging**
