### PR TITLE
Added Changes for cygwin and mingw build scripts in appveyor

### PR DESCRIPTION
**Pull request by anilgit90**
Build files separated in different batch files.

### CODE REVIEW

**Comment by LudovicRousseau** [comment]
Can you merge your 4 commits into just 1?
In 1 commit you remove msvc/appveyor.bat and you add it again in another commit. That is strange.

Use ``git rebase -i HEAD~5`` and squash your commits into 1. Then push again ``git push -f``.
https://help.github.com/articles/about-git-rebase/

You can also change the commit message to use the same format as the other commits for the title. Something like: "AppVeyor: add cycgwin and mingw support"

**Comment by LudovicRousseau** [comment]
Another good idea is to create a new branch for each different pull request you make.

**Comment by anilgit90** [comment]
Sorry if its creating more trouble for you. I am not well versed in git. I only wanted to merge last two commits, but rest of the commits got added as well  how to avoid that?. Next time I will create a branch for every new pull request.

**Comment by mcuee** [comment]
BTW, you only add the configurations for Cygwin and MSYS2 (32/64bit), but
not yet for MinGW.org.

**Comment by anilgit90** [comment]
MinGW builds fail on Appveyor. When I tried the same on my local machine it says the autoreconf version that I am using is not compatible. Hence I did not include the MinGW 32-bit build.

**Comment by mcuee** [comment]
I see. In that case, we can leave out MinGW.org first.

**Comment by LudovicRousseau** [comment]
@anilgit90 no problem for me. Git was also not easy for me when I started. Just read documentation and take your time.

**Comment by anilgit90** [comment]
Merged the patches together as per your recommendation. Is it okay now?

**Comment by LudovicRousseau** [comment]
Not yet finished. But good job.

You still have 2 commits instead of 1 above the 'upstream/master' branch.

All your changes are relaed to AppVeyor. No need to start each comment line by "[AppVeyor]:".
Just use "AppVeyor: fix ...." (without []) on the 1st line (the title), then insert an empty line and continue with normal comments and that will be fine. You can use '-' to enumerate items.

Have a look at the commit message in https://github.com/libusb/libusb/commit/40fb6ff0a0cb67343b722a6b6227f21142cb18cd for a good example.

**Comment by anilgit90** [comment]
Hi, Merged the commits, is the changes proper? Let me know if i missed out anything.

**Comment by LudovicRousseau** [comment]
Committed in https://github.com/libusb/libusb/commit/a42b524731557e3204c31247f0a7be671057d9ef

Thanks a lot

**Pull request closed without merging**
