### PR TITLE
Update the linking path to @executable_path.

### PR DESCRIPTION
**Pull request by olunx**

### CODE REVIEW

**Comment by LudovicRousseau** [comment]
I just fixed the Xcode project using the correct end-of-line.

Can you rebase your patch to the latest git version and submit it again?

**Comment by LudovicRousseau** [comment]
@olunx I have no news since 1 year.
Can you document the problem your patch is trying to solve?

**Comment by hjelmn** [comment]
Considering the translation of his commit message is "Change to a static library" I don't think we want this.

**Comment by LudovicRousseau** [comment]
@hjelmn that is also what I found reading the patch/diff.
Closing.

**Pull request closed without merging**
