### PR TITLE
Fixed VS2010 x64 Builds

### PR DESCRIPTION
**Pull request by anilgit90**
Added separate batch file to process VS2010 builds.

### CODE REVIEW

**Comment by LudovicRousseau** [comment]
@anilgit90 Can you rebase your repository above upstream/master branch to have a cleaner history?
And maybe also merge all your new patches into 1.

See https://www.git-scm.com/book/en/v2/Git-Tools-Rewriting-History or https://help.github.com/articles/about-git-rebase/

**Comment by anilgit90** [comment]
I have merged the patches into one file.

**Comment by hjelmn** [comment]
Can you also rebase of the libusb master to get rid of the merge commit.

**Comment by anilgit90** [comment]
Can you guide me on the same? .I tried it once but end up getting the Merge Log once again.

**Comment by LudovicRousseau** [comment]
@anilgit90 use ``git rebase upstream/master`` and fix any conflict.

Then ``git push --force``. You have to use ``--force`` because that will change the history already available in your github repository.

**Comment by anilgit90** [comment]
Thanks.:)  Grouped the commits in single patch.

**Comment by LudovicRousseau** [comment]
Committed in 40fb6ff0a0cb67343b722a6b6227f21142cb18cd
Thanks

**Pull request closed without merging**
