### PR TITLE
Misc warning fixes, mostly implicit sign conversion

### PR DESCRIPTION
**Pull request by seanm**

### CODE REVIEW

**Comment by tormodvolden** [comment]
Lot of good stuff here. When I add -Wconversion on Linux I see there's plenty to fix up in that backend as well. We should take a stab on this in the next development cycle and see if we can enable -Wconversion all over.

**Comment by tormodvolden** [comment]
@hjelmn Maybe you can comment on the third commit?

**Comment by seanm** [comment]
> @hjelmn Maybe you can comment on the third commit? ("Fixed incorrect interpretation of COM-style Release() return value")

Yeah, that code was definitely wrong, but I'm not certain what the author was trying to do... Hopefully @hjelmn knows...

**Comment by seanm** [comment]
@hjelmn @tormodvolden friendly ping...

**Comment by Droid-MAX** [comment]
I have a vaguely bad feeling about this, could be the next potential supply chain poisoning similar to xz-utils?
And I found that programs built with the libusb-1.0.26 source code at some point in time always output some Libusb-related warning information, which had not been the case before. A warning message appears even after the upgrade to 1.0.27.

**Comment by mcuee** [comment]
@Droid-MAX 

Don't spam the github issues. Thanks.

**Comment by seanm** [comment]
> I have a vaguely bad feeling about this, could be the next potential supply chain poisoning similar to xz-utils?

LOL, nope. But I welcome your code review of this PR to try and prove your baseless insinuation.

@tormodvolden would be nice to get this merged though, then I can go back to addressing some clang-tidy issues.

**Comment by tormodvolden** [comment]
@seanm Thanks for these fixes.

@hjelmn I hope you can take a look at the questions raised in commit d81e80a at some point.

**Comment by seanm** [comment]
@tormodvolden would you merge it now if I removed everything awaiting @hjelmn ?

**Comment by tormodvolden** [comment]
It is already merged. The commit I linked to for hjelmn is in master.

**Pull request closed without merging**
