### PR TITLE
linux_usbfs: Accept sysfs attributes without trailing newline

### PR DESCRIPTION
**Pull request by benzea**
While Linux will always include a newline at the end of an attribute, it
does not really belong to the value itself. In fact, e.g. systemd (udev)
will strip all trailing newline characters, without relying on them to
be there.

Requiring newlines seems unecessary overall. And it caused some trouble
by breaking umockdev based CI tests where the trailing whitespace had
been stripped accidentally.

CC: @jwrdegoede

### CODE REVIEW

**Comment by martinpitt** [comment]
Note that this was a behaviour change/regression in commit c3864c822b - libusb up to 1.0.23 didn't need the newlines either, just 1.0.24 does.

**Comment by dickens** [comment]
This is not classifiable as a regression.  If something is going to simulate/mock sysfs, its behavior should actually mimic that of the real kernel.

**Comment by benzea** [comment]
> This is not classifiable as a regression. If something is going to simulate/mock sysfs, its behavior should actually mimic that of the real kernel.

Of course. The main motivation for me is to avoid painful "fails to build from source" situations for distributions that are easily avoidable this way. And, to be honest, it also simply feels a bit cleaner to me, even if it should be acceptable to rely on the `\n` to be included.

**Comment by martinpitt** [comment]
@dickens: Sure, and it does that now. I just wanted to point out in which version/commit it changed behaviour.

**Pull request closed without merging**
