### PR TITLE
linux: Allow configuration value 0 in descriptor

### PR DESCRIPTION
**Pull request by tormodvolden**
Some buggy devices have a configuration with bConfigurationValue of 0.
This is a violation of the USB specification, but we will try to cope
with it.

Since this value normally means "unconfigured" for GET_CONFIGURATION and
SET_CONFIGURATION requests, your mileage may vary.

Commit e9eec3a6 had introduced stricter checking, and relaxing
it may fix issue #850.

Signed-off-by: Tormod Volden <debian.tormod@gmail.com>

### CODE REVIEW

**Comment by dickens** [comment]
This is a good start, but I'd rather verify that the device actually has a configuration descriptor with a bConfigurationValue of 0.  Then we can distinguish between an unconfigured device and a buggy device.

**Comment by tormodvolden** [comment]
Yup. In the one case that was errorring out before, this is taken care of by the following op_get_config_descriptor_by_value(). In the second, op_get_configuration(), I was thinking the user can deal with it, we are not using that function internally. Does the API require us to do any checks for devices not being configured?

**Comment by tormodvolden** [comment]
I have tested this by modifying a device firmware to have configuration value 0. libusb_get_active_config_descriptor() now returns success. I believe this solves the issue at hand, and as I reasoned in the previous comment, this is all that we have to do.

**Comment by dickens** [comment]
Thanks for the PR.  I've addressed the issue in a more complete manner in f38f09d.

**Pull request closed without merging**
