### PR TITLE
More cleanup, mostly macOS-related, revisit of issue #48

### PR DESCRIPTION
**Pull request by seanm**

### CODE REVIEW

**Comment by seanm** [comment]
@dickens Once again, I don't understand why GitHub shows so many commits here... it's only the 8 from today that I want to get merged... how does one specify which commits should be in a pull request? I don't see any UI for that...

@hjelmn you may want to review this.

**Comment by dickens** [comment]
@seanm it looks like your master branch is a collection of your own commits and several merges of the upstream branch. If you want this to look clean from a PR perspective, you'll have to start with a fresh copy of libusb's master and add these commits from there, then do a force push. We don't use merge commits at all.

**Comment by seanm** [comment]
@dickens ok, thx, I'll try that next time. Is this PR workable as is though? Can you cherry pick from it?

**Comment by dickens** [comment]
@seanm, yes that’s what I did with your last PR.

**Comment by hjelmn** [comment]
I would like to start the release process after these are merged.

**Comment by seanm** [comment]
I have some more changes, but didn't want to put too much into on PR...

**Comment by seanm** [comment]
So @hjelmn , you'll be reviewing/merging these changes?

**Comment by hjelmn** [comment]
Sure, either @dickens or I will do it.

**Comment by seanm** [comment]
OK thx, I just had the impression from your comment that you were maybe expecting @dickens was doing it.  Since many of the changes here are Mac-related, I'd figure you'd especially want to look.  :)

**Comment by dickens** [comment]
@hjelmn everything looks straightforward to me except for bd861cb. If you want to look that over and give the go-ahead, I can merge this and start the release.

**Comment by dickens** [comment]
Unless I hear otherwise, I plan on merging these tomorrow night.

There's one last thing I'm getting in for Windows and it's release time.

**Comment by dickens** [comment]
PR merged via the following commits:

fc00bb7 Misc: Replace "Mac OS X" with "macOS", its current name
6bd5658 darwin: Configure Xcode project to specify tab/space, indent amount
3bffd5c Added some Xcode-related items to .gitignore
0f59214 darwin: Cleanup and fixes related to Mac OS IOUSBLib interface checks
8606571 darwin: Replaced low-level mach API with pthread API
d2ebbf7 darwin: Untangle clock_* API tests from atomics tests
297238c darwin: Changed weirdo fixed-sized typedefs with the usual IOUSBLib.h ones
678a43b core: Fixed clang -Wcomma warning

Thanks for the work!

**Pull request closed without merging**
