### PR TITLE
Added USBI_PRINTFLIKE to allow finding printf format string mistakes

### PR DESCRIPTION
**Pull request by seanm**
Fixed one such misktake

### CODE REVIEW

**Comment by LudovicRousseau** [comment]
OK for me

**Comment by hjelmn** [comment]
Looks good. Will pull it in.

**Comment by hjelmn** [comment]
Still planning to merge this and several others. Been busier than expected the last couple weeks.

**Comment by seanm** [comment]
Don't take this the wrong way, but: you and another core developer have both already reviewed the code. It appears everyone agrees it's acceptable.

Isn't it just a matter of pressing "Merge pull request" in github?  Is there an additional complication because of that 'nano' version thing?  Perhaps some kind of workflow improvement or additional automation could be beneficial here...?

**Comment by hjelmn** [comment]
Yup. Just the nano thing. Just a cherry-pick by one of us. I will try to do it tonight.

**Comment by hjelmn** [comment]
Might be github hooks we can use but it takes me about 10 mins to close out 10 PRs. Would take longer to find the right github hook documentation :).

**Comment by seanm** [comment]
Thanks for the explanation.

I'd argue it's better to figure out the right github hook, though I grant that'll likely take more time in the short term.

I can think of a few downsides to batching:
- it increases the time between someone writing a patch, and other people testing it in mainline. If someone finds a problem, the patch writer's memory will be farther back.
- it makes it harder to test incrementally. ex: I have a nightly script that builds a bleeding-edge version of my app, that uses that day's code of all my dependencies. If everything appears one day to the next, and something breaks, it's harder to regress.

**Comment by hjelmn** [comment]
Yeah. I need to figure out how to use the github tools to handle this. Will try to find the time in the next couple of months. For now I have the first batch of PRs closed. Will work on more tomorrow with an aim for release in two weeks.

**Comment by seanm** [comment]
Thanks!

**Pull request closed without merging**
