### PR TITLE
(test only) collection of PRs from Sean

### PR DESCRIPTION
**Pull request by tormodvolden**

### CODE REVIEW

**Comment by seanm** [comment]
@tormodvolden please don't merge those WIP ones...

**Comment by tormodvolden** [comment]
No worries :) This was more a demonstration and test (using a for loop on all PRs).

**Comment by tormodvolden** [comment]
I may strip down "Replace some uses of soft-deprecated libusb_init() and ...." further for 1.0.27, because there are things to discuss. I want to release 1.0.27 soon and therefore not dive into rabbit holes of reviewing and discussing things that strictly is not required for releasing 1.0.27, which has been due for a long time. There are many great things here and in other PRs that should be released, but i am sure there will be a 1.0.28 also :)

**Comment by mcuee** [comment]
Just FYI.

No issues under Windows 10 x64.

```
MINGW64 /c/work/libusb/libusb_staging
$ make check
Making check in libusb
make[1]: Entering directory '/c/work/libusb/libusb_staging/libusb'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/c/work/libusb/libusb_staging/libusb'
Making check in examples
make[1]: Entering directory '/c/work/libusb/libusb_staging/examples'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/c/work/libusb/libusb_staging/examples'
Making check in tests
make[1]: Entering directory '/c/work/libusb/libusb_staging/tests'
make  check-TESTS
make[2]: Entering directory '/c/work/libusb/libusb_staging/tests'
make[3]: Entering directory '/c/work/libusb/libusb_staging/tests'
PASS: stress.exe
PASS: stress_mt.exe
PASS: set_option.exe
PASS: init_context.exe
============================================================================
Testsuite summary for libusb-1.0 1.0.27-rc1
============================================================================
# TOTAL: 4
# PASS:  4
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[3]: Leaving directory '/c/work/libusb/libusb_staging/tests'
make[2]: Leaving directory '/c/work/libusb/libusb_staging/tests'
make[1]: Leaving directory '/c/work/libusb/libusb_staging/tests'
make[1]: Entering directory '/c/work/libusb/libusb_staging'
make[1]: Leaving directory '/c/work/libusb/libusb_staging
```

**Pull request closed without merging**
