### PR TITLE
fix replacing backslash by sharp in sanitize_path

### PR DESCRIPTION
**Pull request by lo1ol**

### CODE REVIEW

**Comment by lo1ol** [comment]
https://github.com/libusb/libusb/issues/633

**Comment by lo1ol** [comment]
I changed fixed commit. It's all right?

**Comment by pbatard** [comment]
Looks okay to me (haven't tested the code). Note that, for style consistency with existing code, you shouldn't have used use `{` `}` for one liner conditions, but that's no big deal.

I'll let the libusb maintainers decide if they want to apply that pull request.

**Comment by mcuee** [comment]
@pbatard Thanks for the review. I support the merge as well.

**Pull request closed without merging**
