### PR TITLE
tests/set_option: Allow no devices in test_no_discovery

### PR DESCRIPTION
**Pull request by RReverser**
As per discussion in #1374.

### CODE REVIEW

**Comment by tormodvolden** [comment]
Thanks, LGTM.

**Comment by mcuee** [comment]
Yes, this PR should be good to go.

**Review by Youw — APPROVED** [review]

**Comment by RReverser** [comment]
Just in case - I don't have merge rights, one of you should probably merge it :)

**Comment by tormodvolden** [comment]
No worries. I just let things sit a bit and carefully cherry-pick just the most important fixes for the 1.0.27 release. This one is important enough because it avoids confusion during testing and possible downstream build checks.

**Pull request closed without merging**
