### PR TITLE
Refactor initialization and how the default context is handled

### PR DESCRIPTION
**Pull request by dickens**
Highlights for this change:

- `usbi_default_context` is only set if `libusb_init()` is called with `NULL`
- All hotplug related functionality (e.g. initialization, processing) has been moved to hotplug.c
- Backends are simplified by removing initialization mutexes.  Mutual exclusion between `init()/exit()` is provided by `default_context_lock`
- Make hotplug types and functions part of libusbi.h with the common usbi_ prefixes (removes hotplug.h)

Addresses issue highlighted in #855

### CODE REVIEW

**Comment by dickens** [comment]
If there are no objections I will merge this later today.  This also addresses #858.

**Comment by mcuee** [comment]
The code changes are a bit complicated for me to review (after all I am not a programmer), but I agree with the general idea and the clean-up (refactor). So I have no objection with the changes.

**Comment by hjelmn** [comment]
That is quite the PR to review. Would have been nice to have it broken down into multiple commits. Easier to review. Also a lot of unnecessary changes of variable names increases the delta making it more difficult to review.

Overall the changes look good but I have only had a chance to skim them. I need a chance to go through them in more detail.

Also, you have a good description in the PR but the commit message is very light. Can you update it with more detail?

**Comment by matallui** [comment]
Is this fix going to make it to 1.0.25? Been waiting for the fix to be released.

**Comment by mcuee** [comment]
Since Nathan is okay with the fix, I am for the fix to be merged and it is better to be included in the 1.0.25.

**Review by mcuee — APPROVED** [review]

**Comment by mcuee** [comment]
@hjelmn This is the last major pull-request to be merged for 1.0.25 release. If Chris has no time to rework the patches, please help here. Thanks.

**Comment by benzea** [comment]
Just for the record. This change broke gutenprint, as it incorrectly did a `libusb_init(&ctx)` and then continued to call `libusb_get_device_list` with a `NULL` context later on. The proposed fix is https://sourceforge.net/p/gimp-print/mailman/message/37614729/

Previously, this worked, because the created context was also the default, but now it does not work anymore.

See https://bugzilla.redhat.com/show_bug.cgi?id=2055504

For Fedora, I did the nasty thing and worked around it for now. That workaround is unfortunately much worse than the proper fix … but it seems to work https://src.fedoraproject.org/rpms/libusb1/blob/5e2dcc2c62b6603c3db85a783a09cb82af79499e/f/0001-core-Install-first-context-as-implicit-default.patch

**Pull request closed without merging**
