### PR TITLE
windows: Add "or later" to debug print of Windows version 8 (because we can't know)

### PR DESCRIPTION
**Pull request by tormodvolden**
See also discussion in #1021.

### CODE REVIEW

**Review by mcuee — APPROVED** [review]
The change looks to be an improvement over the current codes. I am fine with the changes.

**Comment by mcuee** [comment]
Ref: https://docs.microsoft.com/en-us/windows/win32/sysinfo/operating-system-version
* For applications that have been manifested for Windows 8.1 or Windows 10. Applications not manifested for Windows 8.1 or Windows 10 will return the Windows 8 OS version value (6.2). To manifest your applications for Windows 8.1 or Windows 10, refer to [Targeting your application for Windows](https://docs.microsoft.com/en-us/windows/win32/sysinfo/targeting-your-application-at-windows-8-1).

**Review by mcuee — APPROVED** [review]

**Comment by tormodvolden** [comment]
@mcuee Does it display "11" for you now?

(Never mind the appveyor stuff, I just tested it in the same CI run)

**Comment by mcuee** [comment]
> @mcuee Does it display "11" for you now?

Not yet. How do I add the manifest file? Without the manifest file it still shows Windows 8.

**Comment by tormodvolden** [comment]
I guess the manifest must be declared in the .vcxproj as is done in libwdi. But maybe you can take an application that already has a Windows 11 manifest, and run-time link with your new libusb.dll?

I have now updated the build version threshold to be 20000, like in libwdi. I also added a candidate for #1049 on top because then I can check in the appveyor artifacts that it worked correctly there, and we can test everything with one build.

**Comment by mcuee** [comment]
Adding the manifest file seems to be simpler than what I think.
I just create a simple manifest file from the libwdi example and include it in the project (libusb-1.0.dll, listdevs and xusb). And now it can print the Windows versions.

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"> 
    <!-- If you don't have those in your app, Windows 10's GetVersionEx() -->
    <!-- DELIBERATELY reports the WRONG version... which brings us to     -->
    <!-- tonight's spelling bee: "How do you spell 'spineless morons'?"   -->
    <!-- The answer: "M-I-C-R-O-S-O-F-T; 'spineless morons'!"             -->
    <application>
      <!-- Windows 10 -->
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
      <!-- Windows 8.1 -->
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
      <!-- Windows 8 -->
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
      <!-- Windows 7 -->
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
      <!-- Windows Vista -->
      <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"/> 
    </application> 
  </compatibility>
</assembly>

```

**Comment by mcuee** [comment]
I think the pull request is now good to be merged.

The only question now is whether we want to include the manifest file in the libusb-1.0.dll build or not. It is trivial for the VS build. It seems to be possible with the MinGW as well.

Ref: https://stackoverflow.com/questions/33000158/embed-manifest-file-to-require-administrator-execution-level-with-mingw32

Ref: git has similar manifest file.
https://github.com/git/git/blob/master/compat/win32/git.manifest

**Comment by tormodvolden** [comment]
I think the manifest belongs to the application but it would be an option to add one to our examples/ builds.

**Comment by mcuee** [comment]
> I think the manifest belongs to the application but it would be an option to add one to our examples/ builds.

I agree with you. I think you can merge this pull request. Then we can consider the option to add the manifest to probably the xusb example in the future.

**Comment by tormodvolden** [comment]
Merged.

**Pull request closed without merging**
