### PR TITLE
Do not deprecate libusb_set_debug and libusb_init

### PR DESCRIPTION
**Pull request by mcuee**
Resolve the following two issues.
* https://github.com/libusb/libusb/issues/990
* https://github.com/libusb/libusb/issues/1236

### CODE REVIEW

**Comment by mcuee** [comment]
@tormodvolden and @hjelmn 

Any objections to this PR?

**Comment by hjelmn** [comment]
LGTM

**Comment by tormodvolden** [comment]
I agree to this. We can reconsider marking them deprecated in a last 1.0.x release, if we plan ditching them in 1.1.x. I can merge this next time I am on it.

**Comment by mcuee** [comment]
@tormodvolden 

Since Nathan and you both agree with this, I think it should be okay to merge this.

**Comment by tormodvolden** [comment]
Merged in commit fcf0c710.

**Pull request closed without merging**
